### ISSUE TITLE
[Create a bootable USB stick on Windows] unnecessary and confusing step

### ISSUE THREAD

**Issue by joonas-fi** [canonical-web-and-design/tutorials.ubuntu.com#1020] opened 2019-08-04 16:41 UTC
https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-windows#3

In section "Boot selection and Partition scheme", it advices to select FreeDOS - this is unnecessary and adds to user confusion.

After you'll select the ISO file, the boot selection is switched away from FreeDOS. This is also apparent from the screenshot in the following guide section.

Summary: FreeDOS selection will not be used, and so it is unnecessary and confusing to advice the user to select it.

**Comment by foobarbecue** [comment] 2019-11-24 03:19
Duplicate of https://github.com/canonical-web-and-design/tutorials.ubuntu.com/issues/847

**Comment by steverydz** [comment] 2020-02-07 15:10
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.

**Closed by steverydz** 2020-02-07 15:10 UTC
