### ISSUE TITLE
[Create a bootable USB stick on Windows] Choosing FreeDOS is not necessary

### ISSUE THREAD

**Issue by PerryCodes** [canonical-web-and-design/tutorials.ubuntu.com#1027] opened 2019-08-15 02:44 UTC
Step 4 is titled 'Boot selection and Partition scheme' and starts with the following text:
"Now choose the Boot selection. Choices will be Non bootable and FreeDOS. Since you are creating a bootable Ubuntu device select FreeDOS."

Some sort of correlation between making Ubuntu bootable and selection 'FreeDOS' in the 'Bool selection' field is made here... There is none.

As a matter of fact, once you select the .iso, this field is changed from 'FreeDOS' to your .iso automatically - and is seen in latter screenshots in this tutorial.

I suggest this paragraph be modified to remove the 'FreeDOS' selection.

**Comment by xdavidliu** [comment] 2019-08-25 02:39
I was about to file this exact same bug.

**Comment by foobarbecue** [comment] 2019-11-24 03:19
Duplicate of https://github.com/canonical-web-and-design/tutorials.ubuntu.com/issues/847

**Comment by steverydz** [comment] 2020-02-07 15:10
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.

**Closed by steverydz** 2020-02-07 15:10 UTC
