### ISSUE TITLE
[Create a bootable USB stick on Windows] Correct boot selection option?

### ISSUE THREAD

**Issue by irenkamalova** [canonical-web-and-design/tutorials.ubuntu.com#974] opened 2019-05-12 18:35 UTC
At the step 4, there asked user to choose FreeDOS,
but later, after user choosed an iso-image, there no word about boot selection changed.
So, does user need to do the 4 step? It seems to be redudant.

**Comment by foobarbecue** [comment] 2019-11-24 03:18
Duplicate of https://github.com/canonical-web-and-design/tutorials.ubuntu.com/issues/847

**Comment by steverydz** [comment] 2020-02-07 15:13
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.

**Closed by steverydz** 2020-02-07 15:13 UTC
